[package]
name = "swagger-rustgen"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "swagger-rustgen"

[dependencies]
serde_yaml = "0.8"
serde = { version = "1", features = ["derive"] }
convert_case = "0.5"
